accounts/urls.py
from django.urls import path
from .views import (
    RegistUserView, HomeView, UserLoginView, UserLogoutView,
    UserView
)


app_name = 'accounts'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', RegistUserView.as_view(), name='regist'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),   
    path('user/', UserView.as_view(), name='user'),  
]

book_ranking/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('books/', include('books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from .views import (
    BookListView, BookDetailView,
)

app_name = 'books'
urlpatterns = [
    path('book_list/', BookListView.as_view(), name='book_list'),
    path('book_detail/<int:pk>', BookDetailView.as_view(), name='book_detail'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.urls import reverse_lazy

class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('Enter Email')
        user = self.model(
            username = username,
            email = email
        )        
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self, username, email, password=None):
        user = self.model(
            username = username,
            email = email,
        )
        user.set_password(password)
        user.is_staff = True
        user.is_active = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class Users(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=150)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def get_absolute_url(self):
        return reverse_lazy('accounts:home')

books/models.py
from django.db import models


class Publishers(models.Model):
    name = models.CharField(max_length=1000)

    class Meta:
        db_table = 'publisher'

    def __str__(self):
        return self.name

class Books(models.Model):
    title = models.CharField(max_length=1000)
    author = models.CharField(max_length=1000)
    date_of_publication = models.DateField()
    publisher = models.ForeignKey(
        Publishers, on_delete=models.CASCADE
    )
    url = models.URLField()
    total_point = models.IntegerField()
    yearly_point = models.IntegerField()
    monthly_point = models.IntegerField()

    class Meta:
        db_table = 'book'
    
    def __str__(self):
        return self.title

class Pictures(models.Model):
    picture = models.FileField(upload_to='picture/')
    book = models.ForeignKey(
        Books, on_delete=models.CASCADE
    )
    order = models.IntegerField()

    class Meta:
        db_table = 'picture'
        ordering = ['order']

    def __str__(self):
        return self.book.title + ': ' + str(self.order)

accounts/forms.py
from django import forms
from .models import Users
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import AuthenticationForm


class RegistForm(forms.ModelForm):
    username = forms.CharField(label='名前')
    age = forms.IntegerField(label='年齢', min_value=0)
    email = forms.EmailField(label='メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())

    class Meta:
        model = Users
        fields = ['username', 'age', 'email', 'password']        

    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

# class UserLoginForm(forms.Form):
    # email = forms.EmailField(label='メールアドレス')
    # password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
class UserLoginForm(AuthenticationForm):
    username = forms.EmailField(label='メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    remember = forms.BooleanField(label='ログイン状態を保持する', required=False)

accounts/views.py
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, FormView
from django.views.generic.base import TemplateView, View
from .forms import RegistForm, UserLoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView

class HomeView(TemplateView):
    template_name = 'home.html'

class RegistUserView(CreateView):
    template_name = 'regist.html'
    form_class = RegistForm


class UserLoginView(LoginView):
    template_name = 'user_login.html'
    authentication_form = UserLoginForm

    def form_valid(self, form):
        remember = form.cleaned_data['remember']
        if remember:
            self.request.session.set_expiry(1200000)
        return super().form_valid(form)


class UserLogoutView(LogoutView):
    pass

class UserView(LoginRequiredMixin, TemplateView):
    template_name = 'user.html'

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

books/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

import os
from .models import (
    Books,
)

class BookListView(LoginRequiredMixin, ListView):
    model = Books
    template_name = os.path.join('books', 'book_list.html')

    def get_queryset(self):
        query = super().get_queryset()
        book_title = self.request.GET.get('book_title', None)
        book_author_name = self.request.GET.get('book_author_name', None)
        if book_title:
            query = query.filter(
                title=book_title
            )
        if book_author_name:
            query = query.filter(
                author=book_author_name
            )
        order_by_total = self.request.GET.get('order_by_total', '0')
        if order_by_total == '1':
            query = query.order_by('total_point')
        elif order_by_total == '2':
            query = query.order_by('-total_point')
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book_title'] = self.request.GET.get('book_title', '')
        context['book_author_name'] = self.request.GET.get('book_author_name', '')
        order_by_total = self.request.GET.get('order_by_total', 0)
        if order_by_total == '1':
            context['ascending'] = True
        elif order_by_total == '2':
            context['descending'] = True        
        return context

class BookDetailView(LoginRequiredMixin, DetailView):
    model = Books
    template_name = os.path.join('books', 'book_detail.html')

templates/base.html
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'accounts:home' %}">ホーム</a>
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'accounts:user_logout' %}">ログアウト</a>
        <a class="navbar-brand" href="{% url 'books:book_list' %}">ブック一覧</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
        <a class="navbar-brand" href="{% url 'accounts:regist' %}">ユーザー登録</a>
        {% endif %}
        <a class="navbar-brand" href="{% url 'accounts:user' %}">ユーザー画面</a>
      </nav>
      {% block content %}{% endblock %}
   </body>
</html>

templates/books/book_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="col-6 offset-3">
    <div style="float: left; padding: 0 20px 20px 0">
        {% for picture in object.pictures_set.all %}
            <img width="200px" height="300px" src={{ picture.picture.url }}>
        {% endfor %}
    </div>
    <div>
        <p>タイトル：　{{ object.title }}</p>
        <p>著者：　{{ object.author }}</p>
        <p>出版日：　{{ object.date_of_publication }}</p>
    </div>
</div>
{% endblock %}

templates/books/book_list.html
{% extends 'base.html' %}
{% block content %}
<div class="col-10 offset-1">
<h2>ブック一覧</h2>
<form method="get" action="{% url 'books:book_list' %}">
    <p>タイトル： <input type="text" name="book_title" value="{{ book_title }}"/></p>
    <p>著者： <input type="text" name="book_author_name" value="{{ book_author_name }}"/></p>
    <p>総合ポイントで並び替える：
        昇順<input type="radio" name="order_by_total" value="1" {% if ascending %}checked{% endif %}>
        降順<input type="radio" name="order_by_total" value="2" {% if descending %}checked{% endif %}>
    </p>
    <p><input type="submit" value="実行する"/></p> 
</form>
<table class="table table-striped table-bordered">
<thead>
    <tr>
        <td>タイトル</td>
        <td>著者</td>
        <td>出版日</td>
        <td>出版社</td>
        <td>総合ポイント</td>
        <td>年間ポイント</td>
        <td>月間ポイント</td>
        <td>アマゾンurl</td>
    </tr>
</thead>
<tbody>
{% for book in object_list %}
    <tr>
        <td><a href="{% url 'books:book_detail' pk=book.id %}">{{ book.title }}</a></td>
        <td>{{ book.author }}</td>     
        <td>{{ book.date_of_publication }}</td>
        <td>{{ book.publisher.name }}</td>    
        <td>{{ book.total_point }}P</td>
        <td>{{ book.yearly_point }}P</td>     
        <td>{{ book.monthly_point }}P</td>     
        <td>{{ book.url }}</td>
    </tr>
{% endfor %}
</tbody>
</table>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>ホーム画面です</h1>
{% endblock %}

templates/regist.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="ユーザ登録">
</form>
{% endblock %}

templates/user.html
{% extends 'base.html' %}
{% block content %}
<h1>ユーザー画面です。ログインが必要な画面です。</h1>
{% endblock %}

templates/user_login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="hidden" name="next" value="{{ request.GET.next }}">
   <input type="submit" value="ログイン">
</form>
{% endblock %}